### ISSUE TITLE
フォントコンバーター

### ISSUE THREAD

**Issue by hiz8** [playrjp/playrjp.github.io#12]
サイトへＷｅｂフォントを導入する際の手順。

フォントの返還は[Font Converter](http://www.fontconverter.org/en.html)で、Woff2へは[woff to woff2 converter](https://everythingfonts.com/woff-to-woff2)で行える。

``` css
@font-face {
  font-family: 'webfont';
  src:url('font/webfont.eot');
  src:url('font/webfont.eot?#iefix') format('embedded-opentype'),
      url('font/webfont.woff2') format('woff2')
      url('font/webfont.woff') format('woff'),
      url('font/webfont.ttf') format('truetype'),
      url('font/webfont.svg#icomoon') format('svg');
}
```

IE8以下の対応はもういいかなとも思う。
