### ISSUE TITLE
Webp 導入思案

### ISSUE THREAD

**Issue by hiz8** [playrjp/playrjp.github.io#20]
Webpをさくっと導入できないか思案。
- [Can I use... Support tables for HTML5, CSS3, etc](http://caniuse.com/#search=webp)

取りあえず対応しているのはBlinkブラウザのみだが、モバイル対応へ重きを置くならば価値はありそう。
- [【翻訳】Introduction to WebP - 1000ch.net](https://1000ch.net/posts/2015/introduction-to-webp.html)

Webpの概要と導入の際の未サポートブラウザへのフォールバック方法を解説。
記事内でも言及があるサーバーサイドでの実装が一番よさそうではある。
- [Deploying WebP via Accept Content Negotiation - igvita.com](https://www.igvita.com/2013/05/01/deploying-webp-via-accept-content-negotiation/)

しかしサクっとはできなさそうなので、フロントで実装したい。
今回は`background-image`へのwebp導入を考えているので、記事で紹介されている`<picture>`エレメントを使用する方法も不可。

色々調べると‘@supports‘を利用した方法を発見。
- [Using the WebP image format / blog unblock](https://andywalpole.me/#!/blog/142790/using-webp-image-format)

`@supports`で機能が利用できるか確認し、分岐する手法が紹介されている。
筆者は最終的にModernizrを使用したようだが(そりゃそうだよな…)、今回このためにModernizr入れるのは本末転倒である。
`@supports`面白そうだしカジュアルなのでコレを採用。
- [@supports - CSS | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/@supports)
- [Can I use... Support tables for HTML5, CSS3, etc](http://caniuse.com/#feat=css-featurequeries)

``` css
background-image: url("../img/bg.png");
@supports (background-image: -webkit-image-set(url("../img/bg.webp") 1x)) {
    background-image: -webkit-image-set(url("../img/bg.webp") 1x)
}
```
- [Can I use... Support tables for HTML5, CSS3, etc](http://caniuse.com/#feat=css-image-set)
